Rentacar/Controllers/CarAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.Car;
using Rentacar.BusinessModels.CarImage;
using Rentacar.DataModels;
using Rentacar.Services.Interfaces;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarAdminController : Controller
    {
        private readonly ICarBusinessLogic _cars;
        private readonly ICarManufacturerService _carManufacturers;
        private readonly ICarModelService _carModels;
        private readonly ICarImageBusinessLogic _carImages;
        private readonly ICarBodyTypeBusinessLogic _carTypes;

        public CarAdminController(
            ICarBusinessLogic cars, 
            ICarManufacturerService carManufacturers, 
            ICarModelService carModels, 
            ICarImageBusinessLogic carImages,
            ICarBodyTypeBusinessLogic carTypes)
        {
            _cars = cars;
            _carManufacturers = carManufacturers;
            _carModels = carModels;
            _carImages = carImages;
            _carTypes = carTypes;
        }

        public IActionResult Index()
        {
            return View(_cars.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(_cars.GetCarDetails(id));
            throw new NotImplementedException();
            //return View(_cars.GetById(id));
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            CarCreateBusinessModel car = new CarCreateBusinessModel();
            car.CarBodyTypeList = _carTypes.GetSelectListItems();
            ViewBag.CarManufacturerOptions = _carManufacturers.GetAll();
            return View(car);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(CarCreateBusinessModel car)
        {
            CarDataModel carData = _cars.Insert(car);
            if (carData != null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            CarEditBusinessModel car = _cars.GetCarEditModel(id);
            ViewBag.CarManufacturerOptions = _carManufacturers.GetAll();
            ViewBag.CarModelOptions = _carModels.GetByManufacturerID(car.CarManufacturer.ID);
            car.CarBodyTypeList = _carTypes.GetSelectListItems();
            return View(car);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Edit(CarEditBusinessModel car)
        {
            _cars.Update(car);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (Request.Method == "POST")
            {
                _cars.DeleteByID(id);
                return RedirectToAction("Index");
            }
            return View(_cars.GetCarDetails(id));
        }

        [HttpGet]
        public IActionResult CarImages(int id)
        {
            IEnumerable<CarImageBusinessModel> images = _carImages.GetByCarID(id);
            if (images == null || images.Count() == 0) 
                return RedirectToAction("Details", new { id });
            return View(images);
        }
    }
}

Rentacar/Controllers/CarImageAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.CarImage;
using Rentacar.Services.Interfaces;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarImageAdminController : Controller
    {
        private readonly ICarImageBusinessLogic _images;

        public CarImageAdminController(ICarImageBusinessLogic images)
        {
            _images = images;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            CarImagesCreateBusinessModel images = new CarImagesCreateBusinessModel() { CarID = id };
            return View(images);
        }
        [HttpPost]
        public IActionResult Create(CarImagesCreateBusinessModel imageModel)
        {
            _images.Insert(imageModel);
            return RedirectToAction("CarImages", "CarAdmin", new { id = imageModel.CarID });
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            CarImageBusinessModel image = _images.GetByID(id);
            if (Request.Method == "POST")
            {
                _images.DeleteByID(id);
                return RedirectToAction("CarImages", "CarAdmin", new { ID = image.CarID });
            }
            return View(image);
        }
    }
}

Rentacar/Controllers/CarManufacturerAdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.CarManufacturer;
using Rentacar.DataModels;
using Rentacar.Services.Interfaces;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarManufacturerAdminController : Controller
    {
        private readonly IMapper mapper;
        private readonly ICarManufacturerBusinessLogic _carManufacturers;

        public CarManufacturerAdminController(IMapper _mapper, ICarManufacturerBusinessLogic carManufacturers)
        {
            _mapper = _mapper;
            _carManufacturers = carManufacturers;
        }

        public IActionResult Index()
        {
            return View(_carManufacturers.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(_carManufacturers.GetByID(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CarManufacturerCreateBusinessModel manufacturer)
        {
            _carManufacturers.Insert(manufacturer);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            CarManufacturerBusinessModel manufacturer = _carManufacturers.GetByID(id);
            return View(manufacturer);
        }
        [HttpPost]
        public IActionResult Edit(CarManufacturerBusinessModel manufacturer)
        {
            _carManufacturers.Update(manufacturer);
            return RedirectToAction("Details", new { id = manufacturer.ID });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            CarManufacturerBusinessModel manufacturer = _carManufacturers.GetByID(id);
            return View(manufacturer);
        }
        [HttpPost]
        public IActionResult Delete(CarManufacturerBusinessModel manufacturer)
        {
            _carManufacturers.Delete(manufacturer);
            return RedirectToAction("Index");
        }
    }
}

Rentacar/Controllers/CarModelAdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.CarModel;
using Rentacar.DataModels;
using Rentacar.Services.Interfaces;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarModelAdminController : Controller
    {
        private readonly ICarModelBusinessLogic _carModels;
        private readonly ICarManufacturerBusinessLogic _carManufacturers;

        public CarModelAdminController(
            ICarModelBusinessLogic carModels,
            ICarManufacturerBusinessLogic carManufacturers)
        {
            _carModels = carModels;
            _carManufacturers = carManufacturers;
        }

        public IActionResult Index()
        {
            IEnumerable<CarModelListBusinessModel> models = _carModels.GetAll()
                .OrderBy(m => m.Name)
                .OrderBy(m => m.ManufacturerName);
            return View(models);
        }
        public IActionResult Details(int id)
        {
            return View(_carModels.GetListModelByID(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.ManufacturerOptions = _carManufacturers.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult Create(CarModelCreateBusinessModel model)
        {
            CarModelDataModel modelData = _carModels.Insert(model);
            return RedirectToAction("Details", new { id = modelData.ID });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.ManufacturerOptions = _carManufacturers.GetAll();
            CarModelEditBusinessModel model = _carModels.GetEditModelByID(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(CarModelEditBusinessModel model)
        {
            _carModels.Update(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_carModels.GetListModelByID(id));
        }
        [HttpPost]
        public IActionResult Delete(CarModelListBusinessModel model)
        {
            _carModels.Delete(model);
            return RedirectToAction("Index");
        }

        public JsonResult GetManufacturerModels(int id)
        {
            return Json(_carModels.GetByManufacturerID(id));
        }
    }
}

Rentacar/Views/CarAdmin/CarImages.cshtml
@model IEnumerable<Rentacar.BusinessModels.CarImage.CarImageBusinessModel>

<div class="text-center">
    <a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.First().CarID">Back to car details</a>
</div>

<div class="container text-center justify-content-center d-flex flex-wrap">
    @{ var count = 1; }
    @foreach (var image in Model)
    {
        <div class="card" style="width: 18rem;">
            <img src="@image.Url" class="card-img-top" alt="Image of @image.CarCodeName @count">
            <div class="card-body">
                <a class="btn btn-danger" asp-controller="CarImageAdmin" asp-action="Delete" asp-route-id="@image.ID">Delete</a>
            </div>
        </div>
        count += 1;
    }
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <a class="btn btn-primary align-middle" asp-controller="CarImageAdmin" asp-action="Create" asp-route-id="@Model.First().CarID">+ Add new</a>
        </div>
    </div>
</div>

Rentacar/Views/CarAdmin/Create.cshtml
@model Rentacar.BusinessModels.Car.CarCreateBusinessModel

<h4>CarDataModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="CarManufacturerSelect" class="form-label">Car Manufacturer</label>
                <select id="CarManufacturerSelect" name="CarManufacturer" class="form-select">
                    <option value="0">Select Manufacturer</option>
                    @foreach (var manufacturer in ViewBag.CarManufacturerOptions)
                    {
                        <option value="@manufacturer.ID">@manufacturer.Name</option>
                    }
                </select> 
                <a asp-controller="CarManufacturerAdmin" asp-action="Create" class="btn btn-light">+ Add new</a>
            </div>
            <div class="form-group">
                <label for="CarModelSelect" class="form-label">Car Model</label>
                <select id="CarModelSelect" name="CarModelID" class="form-select" disabled>
                    <option value="0">Select Model</option>
                </select> 
                <a asp-controller="CarModelAdmin" asp-action="Create" class="btn btn-light">+ Add new</a>
            </div>
            <div class="form-group">
                <label asp-for="CarBodyTypeID" class="control-label"></label>
                <select class="form-control" asp-for="CarBodyTypeID" asp-items="@Model.CarBodyTypeList">
                    <option disabled selected>Select car type</option>
                </select>
                <span asp-validation-for="CarBodyTypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LicencePlateNumber" class="control-label"></label>
                <input asp-for="LicencePlateNumber" class="form-control" />
                <span asp-validation-for="LicencePlateNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturedYear" class="control-label"></label>
                <select asp-for="ManufacturedYear" class="form-select">
                    <option value="0">Select Year</option>
                    @{
                        int yer = DateTime.Now.Year;
                    }
                    @while (yer >= 1672)
                    {
                        <option value="@yer">@yer</option>
                        {
                            yer -= 1;
                        }
                    }
                </select>
                <span asp-validation-for="ManufacturedYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodeName" class="control-label"></label>
                <input asp-for="CodeName" class="form-control" />
                <span asp-validation-for="CodeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeatCount" class="control-label"></label>
                <input asp-for="SeatCount" class="form-control" />
                <span asp-validation-for="SeatCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DailyFee" class="control-label"></label>
                <input asp-for="DailyFee" class="form-control" />
                <span asp-validation-for="DailyFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FixedFee" class="control-label"></label>
                <input asp-for="FixedFee" class="form-control" />
                <span asp-validation-for="FixedFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Rentacar/Views/CarAdmin/Delete.cshtml
@model Rentacar.BusinessModels.Car.CarDetailsBusinessModel

<h3>Kill @Model.CodeName?</h3>
<div>
    <h4>CarDetailsBusinessModel</h4>
    <hr />
    @await Html.PartialAsync("_ImageCarousel", Model.Images)
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LicencePlateNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicencePlateNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarManufacturerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarManufacturerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarModelName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturedYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturedYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CodeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DailyFee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DailyFee)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FixedFee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FixedFee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Rentacar/Views/CarAdmin/Details.cshtml
@model Rentacar.BusinessModels.Car.CarDetailsBusinessModel

<div>
    <h4>CarDetailsBusinessModel</h4>
    <hr />
    @await Html.PartialAsync("_ImageCarousel", Model.Images)
    @if (Model.Images == null || Model.Images.Count() == 0)
    {
        <a class="btn btn-primary" asp-controller="CarImageAdmin" asp-action="Create" asp-route-id="@Model.ID">+ Add Image</a>
    } else
    {
        <a class="btn btn-primary" asp-action="CarImages" asp-route-id="@Model.ID">Edit Images</a>
    }
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LicencePlateNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicencePlateNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarManufacturerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarManufacturerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarModelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturedYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturedYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarBodyTypeValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarBodyTypeValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SeatCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SeatCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DailyFee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DailyFee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FixedFee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FixedFee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Rentacar/Views/CarAdmin/Edit.cshtml
@model Rentacar.BusinessModels.Car.CarEditBusinessModel

<h4>CarEditBusinessModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="LicencePlateNumber" class="control-label"></label>
                <input asp-for="LicencePlateNumber" class="form-control" />
                <span asp-validation-for="LicencePlateNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="CarManufacturerSelect" class="form-label">Car Manufacturer</label>
                <select id="CarManufacturerSelect" name="CarManufacturer" class="form-select">
                    <option value="0">Select Manufacturer</option>
                    @foreach (var manufacturer in ViewBag.CarManufacturerOptions)
                    {
                        @if (Model.CarManufacturer.ID == manufacturer.ID)
                        {
                            <option selected value="@manufacturer.ID">@manufacturer.Name</option>
                        } else
                        {
                            <option value="@manufacturer.ID">@manufacturer.Name</option>
                        }
                    }
                </select>
                <a asp-controller="CarManufacturerAdmin" asp-action="Create" class="btn btn-light">+ Add new</a>
            </div>
            <div class="form-group">
                <label for="CarModelSelect" class="form-label">Car Model</label>
                <select id="CarModelSelect" name="CarModelID" class="form-select">
                    <option value="0">Select Model</option>
                    @foreach (var carModel in ViewBag.CarModelOptions)
                    {
                        @if (Model.CarModel.ID == carModel.ID)
                        {
                            <option selected value="@carModel.ID">@carModel.Name</option>
                        } else
                        {
                            <option value="@carModel.ID">@carModel.Name</option>
                        }
                    }
                </select>
                <a asp-controller="CarModelAdmin" asp-action="Create" class="btn btn-light">+ Add new</a>
            </div>
            <div class="form-group">
                <label asp-for="CarBodyTypeID" class="control-label"></label>
                <select class="form-control" asp-for="CarBodyTypeID" asp-items="@Model.CarBodyTypeList">
                    <option disabled selected>Select car type</option>
                </select>
                <span asp-validation-for="CarBodyTypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturedYear" class="control-label"></label>
                <select asp-for="ManufacturedYear" class="form-select">
                    <option value="0">Select Year</option>
                    @{
                        int yer = DateTime.Now.Year;
                    }
                    @while (yer >= 1672)
                    {
                        <option value="@yer">@yer</option>
                        {
                            yer -= 1;
                        }
                    }
                </select>
                <span asp-validation-for="ManufacturedYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodeName" class="control-label"></label>
                <input asp-for="CodeName" class="form-control" />
                <span asp-validation-for="CodeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeatCount" class="control-label"></label>
                <input asp-for="SeatCount" class="form-control" />
                <span asp-validation-for="SeatCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DailyFee" class="control-label"></label>
                <input asp-for="DailyFee" class="form-control" />
                <span asp-validation-for="DailyFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FixedFee" class="control-label"></label>
                <input asp-for="FixedFee" class="form-control" />
                <span asp-validation-for="FixedFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Rentacar/Views/CarAdmin/Index.cshtml
@model IEnumerable<Rentacar.BusinessModels.Car.CarListBusinessModel>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ID)</th>
            <th>@Html.DisplayNameFor(model => model.LicencePlateNumber)</th>
            <th>@Html.DisplayNameFor(model => model.ManufacturedYear)</th>
            <th>@Html.DisplayNameFor(model => model.CarManufacturerName)</th>
            <th>@Html.DisplayNameFor(model => model.CarModelName)</th>
            <th>@Html.DisplayNameFor(model => model.CarBodyTypeValue)</th>
            <th>@Html.DisplayNameFor(model => model.CodeName)</th>
            <th>@Html.DisplayNameFor(model => model.DailyFee)</th>
            <th>@Html.DisplayNameFor(model => model.FixedFee)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.ID)</td>
            <td>@Html.DisplayFor(modelItem => item.LicencePlateNumber)</td>
            <td>@Html.DisplayFor(modelItem => item.ManufacturedYear)</td>
            <th>@Html.DisplayFor(modelItem => item.CarManufacturerName)</th>
            <th>@Html.DisplayFor(modelItem => item.CarModelName)</th>
            <th>@Html.DisplayFor(modelItem => item.CarBodyTypeValue)</th>
            <td>@Html.DisplayFor(modelItem => item.CodeName)</td>
            <td>@Html.DisplayFor(modelItem => item.DailyFee)</td>
            <td>@Html.DisplayFor(modelItem => item.FixedFee)</td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>