Rentacar/Controllers/CarAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.Car;
using Rentacar.BusinessModels.CarImage;
using Rentacar.DataModels;
using Rentacar.Services.Interfaces;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarAdminController : Controller
    {
        private readonly ICarBusinessLogic _cars;
        private readonly ICarManufacturerService _carManufacturers;
        private readonly ICarModelService _carModels;
        private readonly ICarImageBusinessLogic _carImages;
        private readonly ICarBodyTypeBusinessLogic _carTypes;

        public CarAdminController(
            ICarBusinessLogic cars, 
            ICarManufacturerService carManufacturers, 
            ICarModelService carModels, 
            ICarImageBusinessLogic carImages,
            ICarBodyTypeBusinessLogic carTypes)
        {
            _cars = cars;
            _carManufacturers = carManufacturers;
            _carModels = carModels;
            _carImages = carImages;
            _carTypes = carTypes;
        }

        public IActionResult Index()
        {
            return View(_cars.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(_cars.GetCarDetails(id));
            throw new NotImplementedException();
            //return View(_cars.GetById(id));
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            CarCreateBusinessModel car = new CarCreateBusinessModel();
            car.CarBodyTypeList = _carTypes.GetSelectListItems();
            ViewBag.CarManufacturerOptions = _carManufacturers.GetAll();
            return View(car);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(CarCreateBusinessModel car)
        {
            CarDataModel carData = _cars.Insert(car);
            if (carData != null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            CarEditBusinessModel car = _cars.GetCarEditModel(id);
            ViewBag.CarManufacturerOptions = _carManufacturers.GetAll();
            ViewBag.CarModelOptions = _carModels.GetByManufacturerID(car.CarManufacturer.ID);
            car.CarBodyTypeList = _carTypes.GetSelectListItems();
            return View(car);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Edit(CarEditBusinessModel car)
        {
            _cars.Update(car);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (Request.Method == "POST")
            {
                _cars.DeleteByID(id);
                return RedirectToAction("Index");
            }
            return View(_cars.GetCarDetails(id));
        }

        [HttpGet]
        public IActionResult CarImages(int id)
        {
            IEnumerable<CarImageBusinessModel> images = _carImages.GetByCarID(id);
            if (images == null || images.Count() == 0) 
                return RedirectToAction("Details", new { id });
            return View(images);
        }
    }
}

Rentacar/Controllers/CarModelAdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.CarModel;
using Rentacar.DataModels;
using Rentacar.Services.Interfaces;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarModelAdminController : Controller
    {
        private readonly ICarModelBusinessLogic _carModels;
        private readonly ICarManufacturerBusinessLogic _carManufacturers;

        public CarModelAdminController(
            ICarModelBusinessLogic carModels,
            ICarManufacturerBusinessLogic carManufacturers)
        {
            _carModels = carModels;
            _carManufacturers = carManufacturers;
        }

        public IActionResult Index()
        {
            IEnumerable<CarModelListBusinessModel> models = _carModels.GetAll()
                .OrderBy(m => m.Name)
                .OrderBy(m => m.ManufacturerName);
            return View(models);
        }
        public IActionResult Details(int id)
        {
            return View(_carModels.GetListModelByID(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.ManufacturerOptions = _carManufacturers.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult Create(CarModelCreateBusinessModel model)
        {
            CarModelDataModel modelData = _carModels.Insert(model);
            return RedirectToAction("Details", new { id = modelData.ID });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.ManufacturerOptions = _carManufacturers.GetAll();
            CarModelEditBusinessModel model = _carModels.GetEditModelByID(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(CarModelEditBusinessModel model)
        {
            _carModels.Update(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_carModels.GetListModelByID(id));
        }
        [HttpPost]
        public IActionResult Delete(CarModelListBusinessModel model)
        {
            _carModels.Delete(model);
            return RedirectToAction("Index");
        }

        public JsonResult GetManufacturerModels(int id)
        {
            return Json(_carModels.GetByManufacturerID(id));
        }
    }
}

Rentacar/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.Car;
using Rentacar.BusinessModels.Reservation;

namespace Rentacar.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ICarBusinessLogic _cars;
        private readonly IReservationBusinessLogic _reservations;
        private readonly IUserInfoBusinessLogic _userInfo;
        private readonly ICarBodyTypeBusinessLogic _carTypes;
        private readonly UserManager<IdentityUser> _userManager;

        public ReservationController(
            ICarBusinessLogic cars,
            IReservationBusinessLogic reservations,
            IUserInfoBusinessLogic userInfo,
            ICarBodyTypeBusinessLogic carTypes,
            UserManager<IdentityUser> userManager)
        {
            _cars = cars;
            _reservations = reservations;
            _userInfo = userInfo;
            _carTypes = carTypes;
            _userManager = userManager;
        }


        public IActionResult Info()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            IdentityUser user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            List<ReservationDetailsBusinessModel> reservations = _reservations.GetbyUser(user.Id).ToList();
            return View(reservations);
        }

        public async Task<IActionResult> Details(int id)
        {
            IdentityUser requestUser = await _userManager.GetUserAsync(HttpContext.User);
            if (requestUser == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }

            ReservationDetailsBusinessModel reservation = _reservations.GetDetails(id);
            if (reservation == null)
                return StatusCode(StatusCodes.Status404NotFound);

            var userInfo = _userInfo.GetDetailsByID(reservation.UserInfoID);
            IdentityUser reservationUser = await _userManager.FindByIdAsync(userInfo.User.Id);

            if (requestUser != reservationUser)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            return View(reservation);
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.CarTypes = _carTypes.GetSelectListItems();
            ReservationCreateBusinessModel reservation = new ReservationCreateBusinessModel();
            reservation.UserInfoID = id;
            return View(reservation);
        }
        [HttpPost]
        public async Task<IActionResult> Create(ReservationCreateBusinessModel reservation)
        {
            IdentityUser userInfoUser = await _userInfo.GetUserByUserInfoIDAsync(reservation.UserInfoID);
            IdentityUser requestUser = await _userManager.GetUserAsync(HttpContext.User);
            if (requestUser != userInfoUser)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }
            ReservationDetailsBusinessModel reservationDetails = _reservations.Insert(reservation);
            return RedirectToAction("Details", new { id = reservationDetails.ID });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ReservationEditBusinessModel reservation = _reservations.GetEdit(id);
            ViewBag.AvailableCars = _cars.GetAvailable(reservation);
            return View(reservation);
        }
        [HttpPost]
        public IActionResult Edit(ReservationEditBusinessModel reservation)
        {
            _reservations.Update(reservation);
            return RedirectToAction("Details", new { id = reservation.ID });
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (Request.Method.ToLower() == "post")
            {
                _reservations.DeleteByID(id);
                return RedirectToAction("Index", "Home");
            }
            ReservationDetailsBusinessModel reservation = _reservations.GetDetails(id);
            if (reservation == null)
                return StatusCode(StatusCodes.Status404NotFound);
            return View(reservation);
        }

        public IActionResult Confirm(int id)
        {
            if (_reservations.Confirm(id))
            {
                return RedirectToAction("Details", new {id = id});
            }
            return StatusCode(StatusCodes.Status418ImATeapot);
        }

        public IActionResult FindAvailableCars(ReservationCreateBusinessModel reservation)
        {
            //Console.WriteLine($"The start date is {reservation.ReservationBegin}");
            IEnumerable<CarDetailsBusinessModel> cars =  _cars.GetAvailable(reservation);
            return PartialView("_FindAvailableCars", cars);
        }

        public IActionResult CarDetailsModal(int id)
        {
            CarDetailsBusinessModel car = _cars.GetCarDetails(id);
            return PartialView("_CarDetailsModal", car);
        }
    }
}

Rentacar/Controllers/RoleAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rentacar.BusinessModels.Role;

namespace Rentacar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public RoleAdminController(
            RoleManager<IdentityRole> roleManager,
            UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            IEnumerable<IdentityRole> roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if (!ModelState.IsValid)
            {
                return View(role);
            }
            IdentityResult result = await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                return View(role);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(IdentityRole role)
        {
            throw new NotImplementedException();
            if (!ModelState.IsValid)
            {
                return View(role);
            }
            IdentityResult result = await _roleManager.UpdateAsync(role);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                return View(role);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(IdentityRole role)
        {
            IdentityRole adminRole = await _roleManager.FindByNameAsync("Admin");
            if (adminRole != null && (role.Id == adminRole.Id || role.Name == adminRole.Name))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            IdentityResult result = await _roleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UserRoles(string? q)
        {
            IEnumerable<IdentityUser> users = _userManager.Users;
            if (q != null)
            {
                users = users.Where(u => u.Email.ToLower().Contains(q));
            }
            users = users.ToList();
            List< Tuple < IdentityUser, List<string> > > userRoles = new List<Tuple<IdentityUser, List<string>>>();
            foreach (IdentityUser user in users)
            {
                List<string> roles = (await _userManager.GetRolesAsync(user)).ToList();
                userRoles.Add(Tuple.Create(user, roles));
            }
            return View(userRoles);
        }

        [HttpGet]
        public async Task<IActionResult> AssignRole(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            List<string> roles = (await _userManager.GetRolesAsync(user)).ToList();
            List<SelectListItem> roleList = new List<SelectListItem>();
            foreach (var role in _roleManager.Roles)
            {
                roleList.Add(new SelectListItem(role.Name, role.Name));
            }

            RoleAssignBusinessModel model = new RoleAssignBusinessModel() {
                UserID = user.Id, 
                UserEmail = user.Email, 
                Roles = roles, 
                RoleList = roleList
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(RoleAssignBusinessModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            IdentityUser user = await _userManager.FindByIdAsync(model.UserID);
            if (user == null || model.ToggledRole == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            IdentityRole role = await _roleManager.FindByNameAsync(model.ToggledRole);
            if (role == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            IdentityUser requestUser = await _userManager.GetUserAsync(HttpContext.User);
            bool isAdmin = await _userManager.IsInRoleAsync(requestUser, "Admin");
            IdentityRole adminRole = await _roleManager.FindByNameAsync("Admin");
            if (requestUser == user && isAdmin && role == adminRole)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }
            IdentityResult result;
            if (await _userManager.IsInRoleAsync(user, role.Name))
            {
                result = await _userManager.RemoveFromRoleAsync(user, role.Name);
            } else
            {
                result = await _userManager.AddToRoleAsync(user, role.Name);
            }
            if (result.Succeeded)
            {
                return RedirectToAction("AssignRole", new { id = user.Id });
            }
            return StatusCode(StatusCodes.Status500InternalServerError);
        }
    }
}

Rentacar/Views/Shared/_ImageCarousel.cshtml
@model IEnumerable<Rentacar.DataModels.CarImageDataModel>

<div id="carImages" class="carousel slide w-25">
    <div class="carousel-indicators">
        @if (Model != null && Model.Count() > 1)
        {
            var count = 0;
            var countPlus1 = 1;
            @foreach (var image in Model)
            {
                @if (count == 0)
                {
                    <button type="button" data-bs-target="#carImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                }
                else
                {
                    <button type="button" data-bs-target="#carImages" data-bs-slide-to="@count" aria-label="Slide @countPlus1"></button>
                }
                count += 1;
                countPlus1 = count + 1;
            }
        }
    </div>
    <div class="carousel-inner">
        @if (Model != null && Model.Count() > 0)
        {
            var count = 0;
            var countPlus1 = 1;
            foreach (var image in Model)
            {
                if (count == 0)
                {
                    <div class="carousel-item active">
                        <img src="@image.Url" class="d-block w-100" alt="Image of @image.Car.CodeName @countPlus1">
                    </div>
                }
                else
                {
                    <div class="carousel-item">
                        <img src="@image.Url" class="d-block w-100" alt="Image of @image.Car.CodeName @countPlus1">
                    </div>
                }
                count += 1;
                countPlus1 = count + 1;
            }
        }
        else
        {
            <div class="carousel-item active">
                <img src="/img/Car/default.png" class="d-block w-100" alt="No image available">
            </div>
        }
    </div>
    @if (Model != null && Model.Count() > 1)
    {
        <button class="carousel-control-prev" type="button" data-bs-target="#carImages" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carImages" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    }
</div>

Rentacar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rentacar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Rentacar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rentacar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if (!Context.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Info">Reserve a car</a>
                            </li>
                        }
                        @if (Context.User.IsInRole("Admin"))
                        {
                            <div class="nav-item dropdown d-flex">
                                <button class="btn btn-light" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li><a class="dropdown-item text-dark" asp-controller="RoleAdmin" asp-action="Index">RoleAdmin</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="CarAdmin" asp-action="Index">CarAdmin</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="CarModelAdmin" asp-action="Index">CarModelAdmin</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="CarManufacturerAdmin" asp-action="Index">CarManufacturerAdmin</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="ReservationAdmin" asp-action="Index">ReservationAdmin</a></li>
                                </ul>
                            </div>
                        }
                        
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarAdmin" asp-action="Index">CarAdmin</a>
                        </li> *@
                    </ul>
                </div>
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <div class="nav-item dropdown d-flex">
                        <button class="btn btn-light" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><div class="dropdown-item text-dark">@Context.User.Identity.Name</div></li>
                            <li><a class="dropdown-item text-dark" asp-controller="Reservation" asp-action="Index">My Reservations</a></li>
                            <li><a class="dropdown-item text-dark" asp-area="identity" asp-page="/Account/logout">Logout</a></li>
                        </ul>
                    </div>
                } else
                {
                    <div class="nav-item dropdown d-flex">
                        <button class="btn btn-light" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item text-dark" asp-area="identity" asp-page="/Account/login">Login</a></li>
                        </ul>
                    </div>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Rentacar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>