Rentacar/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.Car;
using Rentacar.BusinessModels.Reservation;

namespace Rentacar.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ICarBusinessLogic _cars;
        private readonly IReservationBusinessLogic _reservations;
        private readonly IUserInfoBusinessLogic _userInfo;
        private readonly ICarBodyTypeBusinessLogic _carTypes;
        private readonly UserManager<IdentityUser> _userManager;

        public ReservationController(
            ICarBusinessLogic cars,
            IReservationBusinessLogic reservations,
            IUserInfoBusinessLogic userInfo,
            ICarBodyTypeBusinessLogic carTypes,
            UserManager<IdentityUser> userManager)
        {
            _cars = cars;
            _reservations = reservations;
            _userInfo = userInfo;
            _carTypes = carTypes;
            _userManager = userManager;
        }


        public IActionResult Info()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            IdentityUser user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            List<ReservationDetailsBusinessModel> reservations = _reservations.GetbyUser(user.Id).ToList();
            return View(reservations);
        }

        public async Task<IActionResult> Details(int id)
        {
            IdentityUser requestUser = await _userManager.GetUserAsync(HttpContext.User);
            if (requestUser == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }

            ReservationDetailsBusinessModel reservation = _reservations.GetDetails(id);
            if (reservation == null)
                return StatusCode(StatusCodes.Status404NotFound);

            var userInfo = _userInfo.GetDetailsByID(reservation.UserInfoID);
            IdentityUser reservationUser = await _userManager.FindByIdAsync(userInfo.User.Id);

            if (requestUser != reservationUser)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            return View(reservation);
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.CarTypes = _carTypes.GetSelectListItems();
            ReservationCreateBusinessModel reservation = new ReservationCreateBusinessModel();
            reservation.UserInfoID = id;
            return View(reservation);
        }
        [HttpPost]
        public async Task<IActionResult> Create(ReservationCreateBusinessModel reservation)
        {
            IdentityUser userInfoUser = await _userInfo.GetUserByUserInfoIDAsync(reservation.UserInfoID);
            IdentityUser requestUser = await _userManager.GetUserAsync(HttpContext.User);
            if (requestUser != userInfoUser)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }
            ReservationDetailsBusinessModel reservationDetails = _reservations.Insert(reservation);
            return RedirectToAction("Details", new { id = reservationDetails.ID });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ReservationEditBusinessModel reservation = _reservations.GetEdit(id);
            ViewBag.AvailableCars = _cars.GetAvailable(reservation);
            return View(reservation);
        }
        [HttpPost]
        public IActionResult Edit(ReservationEditBusinessModel reservation)
        {
            _reservations.Update(reservation);
            return RedirectToAction("Details", new { id = reservation.ID });
        }

        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (Request.Method.ToLower() == "post")
            {
                _reservations.DeleteByID(id);
                return RedirectToAction("Index", "Home");
            }
            ReservationDetailsBusinessModel reservation = _reservations.GetDetails(id);
            if (reservation == null)
                return StatusCode(StatusCodes.Status404NotFound);
            return View(reservation);
        }

        public IActionResult Confirm(int id)
        {
            if (_reservations.Confirm(id))
            {
                return RedirectToAction("Details", new {id = id});
            }
            return StatusCode(StatusCodes.Status418ImATeapot);
        }

        public IActionResult FindAvailableCars(ReservationCreateBusinessModel reservation)
        {
            //Console.WriteLine($"The start date is {reservation.ReservationBegin}");
            IEnumerable<CarDetailsBusinessModel> cars =  _cars.GetAvailable(reservation);
            return PartialView("_FindAvailableCars", cars);
        }

        public IActionResult CarDetailsModal(int id)
        {
            CarDetailsBusinessModel car = _cars.GetCarDetails(id);
            return PartialView("_CarDetailsModal", car);
        }
    }
}

Rentacar/Controllers/UserInfoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rentacar.BusinessLogic.Interfaces;
using Rentacar.BusinessModels.UserInfo;

namespace Rentacar.Controllers
{
    [Authorize]
    public class UserInfoController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserInfoBusinessLogic _userInfo;
        private readonly IIdentificationDocumentTypeBusinessLogic _identificationTypes;

        public UserInfoController(
            UserManager<IdentityUser> userManager,
            IUserInfoBusinessLogic userInfo,
            IIdentificationDocumentTypeBusinessLogic identificationTypes)
        {
            _userManager = userManager;
            _userInfo = userInfo;
            _identificationTypes = identificationTypes;
        }
        public async Task<IActionResult> Index()
        {
            if (!(HttpContext.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("Create");
            }

            IdentityUser user = await _userManager.GetUserAsync(HttpContext.User);
            IEnumerable<UserInfoDetailsBusinessModel> userInfo = _userInfo.GetDetailsByUserID(user.Id);

            if (userInfo == null || userInfo.Count() == 0)
            {
                return RedirectToAction("Create");
            }
            return View(userInfo);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(_userInfo.GetDetailsByID(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.IdentificationDocumentTypeOptions = _identificationTypes.GetAll();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(UserInfoCreateBusinessModel userInfo)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                userInfo.User = await _userManager.GetUserAsync(HttpContext.User);
            }

            _userInfo.Insert(userInfo);
            return RedirectToAction("index");
        }
    }
}

Rentacar/Views/Reservation/Create.cshtml
@model Rentacar.BusinessModels.Reservation.ReservationCreateBusinessModel


<h4>ReservationDataModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <div class="col-auto">
            <select class="form-control" id="carTypeFilter" asp-items="@ViewBag.CarTypes">
                <option disabled selected>Pick car type</option>
            </select>
            <label for="carTypeFilter">Car Type</label>
        </div>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="UserInfoID" />
            <input id="carIDHiddenInput" type="hidden" asp-for="CarID" />

            <div class="form-group">
                <label asp-for="ReservationBegin" class="control-label"></label>
                <input asp-for="ReservationBegin" class="form-control" />
                <span asp-validation-for="ReservationBegin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationEnd" class="control-label"></label>
                <input asp-for="ReservationEnd" class="form-control" />
                <span asp-validation-for="ReservationEnd" class="text-danger"></span>
            </div>
            <div id="findAvailableCars" class="btn btn-primary">Find available cars</div>
        </form>
    </div>
</div>

<div id="availableCarsContainer" class="container justify-content-center d-flex flex-wrap">

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<!-- Modal Dialog -->
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel">...</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="modalBody" class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                <button id="modalConfirm" type="button" class="btn">...</button>
            </div>
        </div>
    </div>
</div>

Rentacar/Views/Reservation/Delete.cshtml
@model Rentacar.BusinessModels.Reservation.ReservationDetailsBusinessModel

<div>
    <h4>CarDetailsBusinessModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationBegin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReservationBegin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationEnd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReservationEnd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserInfoID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserInfoID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusValue)
        </dd>
    </dl>
</div>
<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.ID">Back</a>
        <input class="btn btn-danger" type="submit" value="Confirm" />
    </form>
</div>

Rentacar/Views/Reservation/Details.cshtml
@model Rentacar.BusinessModels.Reservation.ReservationDetailsBusinessModel

<div>
    @if (Model.StatusValue.ToLower() == "cart")
    {
        <h4>Confirm Reservation Details</h4>
    } else
    {
        <h4>Overview</h4>
    }
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationBegin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReservationBegin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReservationEnd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReservationEnd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserInfoID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserInfoID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusValue)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model?.ID">Cancel Reservation</a>
    @if (Model.StatusValue.ToLower() == "cart")
    {
        <a class="btn btn-warning" asp-action="Confirm" asp-route-id="@Model?.ID">Confirm</a>
    }
    <a asp-action="Edit" asp-route-id="@Model?.ID">Change car</a> |
    <a asp-action="Index">Back to List</a>
</div>

Rentacar/Views/Reservation/Edit.cshtml
@model Rentacar.BusinessModels.Reservation.ReservationEditBusinessModel

@{
    IEnumerable<Rentacar.BusinessModels.Car.CarDetailsBusinessModel> availableCars = ViewBag.AvailableCars;

}

<h4>ReservationDataModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="UserInfoID" />
            <input id="carIDHiddenInput" type="hidden" asp-for="CarID" />
        </form>
    </div>
</div>

<div id="availableCarsContainer" class="container justify-content-center d-flex flex-wrap">
    @await Html.PartialAsync("_FindAvailableCars", availableCars)
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<!-- Modal Dialog -->
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel">...</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="modalBody" class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                <button id="modalConfirm" type="button" class="btn">...</button>
            </div>
        </div>
    </div>
</div>

Rentacar/Views/Reservation/FindAvailableCars.cshtml
@model IEnumerable<Rentacar.BusinessModels.Car.CarDetailsBusinessModel>

@foreach (var car in Model)
{
    <div class="card" style="width: 18rem;">
        @await Html.PartialAsync("_ImageCarousel", car.Images)
        <div class="card-body">
        </div>
    </div>
}

Rentacar/Views/Reservation/Index.cshtml
@model List<Rentacar.BusinessModels.Reservation.ReservationDetailsBusinessModel>

<h4> Your reservations </h4>

@if (!(Model.Count > 0))
{
    <h5>You have not reserved any cars.</h5>
    <a class="btn btn-primary" asp-controller="UserInfo" asp-action="Index">Reserve a car</a>
} else
{
    @for (int i = 0; i < Model.Count; i++)
    {
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model[i].ID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model[i].ID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model[i].ReservationBegin)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model[i].ReservationBegin)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model[i].ReservationEnd)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model[i].ReservationEnd)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model[i].CarID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model[i].CarID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model[i].UserInfoID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model[i].UserInfoID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model[i].StatusValue)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model[i].StatusValue)
            </dd>
        </dl>
        if (Model[i].StatusValue.ToLower() == "cart")
        {
            <p class="alert alert-warning" >Reservation pending confirmation from user. Go to details to confirm reservation.</p>
        }
        <p>
            <a class="btn btn-primary" asp-action="Details" asp-route-ID="@Model[i].ID">Details</a>
        </p>
    }
}

Rentacar/Views/Reservation/Info.cshtml
<div class="container">
    <p>
        In order to reserve a car you will need to input a valid form of identification 
        which will be used to confirm your identity at the physical service location, 
        then you will be able to select the start and end dates of the time period 
        during which you want a car to be rented to you, then you will be shown the cars 
        which are available for that time period. Once you select a car from the list, 
        <s>you will be asked to provide a payment method.</s>
    </p>
    @if (!(Context.User.Identity.IsAuthenticated) || Context.User.Identity.IsAuthenticated == null)
    {
        <p>
            You do not need to be logged into an account to reserve a car however 
            being logged in will allow Rentacar™ to remember your credentials for
            the next time you want to use our service.
        </p>
    }
    <a class="btn btn-primary" asp-controller="UserInfo" asp-action="Index">Continue</a>
</div>

Rentacar/Views/Reservation/_CarDetailsModal.cshtml
@model Rentacar.BusinessModels.Car.CarDetailsBusinessModel

@await Html.PartialAsync("_CarSelectionCarousel", Model.Images)
<hr />
<div class="container-fluid">
    <dl class="row">
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.LicencePlateNumber)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.LicencePlateNumber)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.CarManufacturerName)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.CarManufacturerName)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.CarModelName)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.CarModelName)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.ManufacturedYear)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.ManufacturedYear)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.CodeName)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.CodeName)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.DailyFee)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.DailyFee)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.FixedFee)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.FixedFee)
        </dd>
        <dt class="col-sm-5">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class="col-sm-5">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
    </dl>
</div>
</div>

Rentacar/Views/Reservation/_CarSelectionCarousel.cshtml
@model IEnumerable<Rentacar.DataModels.CarImageDataModel>

<div>
    <div id="carImages" class="carousel slide w-100">
        <div class="carousel-indicators">
            @if (Model != null && Model.Count() > 1)
            {
                var count = 0;
                var countPlus1 = 1;
                @foreach (var image in Model)
                {
                    @if (count == 0)
                    {
                        <button type="button" data-bs-target="#carImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    }
                    else
                    {
                        <button type="button" data-bs-target="#carImages" data-bs-slide-to="@count" aria-label="Slide @countPlus1"></button>
                    }
                    count += 1;
                    countPlus1 = count + 1;
                }
            }
        </div>
        <div class="carousel-inner">
            @if (Model != null && Model.Count() > 0)
            {
                var count = 0;
                var countPlus1 = 1;
                foreach (var image in Model)
                {
                    if (count == 0)
                    {
                        <div class="carousel-item active">
                            <img src="@image.Url" class="card-img-top d-block w-100" alt="Image of @image.Car.CodeName @countPlus1">
                        </div>
                    }
                    else
                    {
                        <div class="carousel-item">
                            <img src="@image.Url" class="card-img-top d-block w-100" alt="Image of @image.Car.CodeName @countPlus1">
                        </div>
                    }
                    count += 1;
                    countPlus1 = count + 1;
                }
            }
            else
            {
                <div class="card-img-top carousel-item active">
                    <img src="/img/Car/default.png" class="card-img-top d-block w-100" alt="No image available">
                </div>
            }
        </div>
        @if (Model != null && Model.Count() > 1)
        {
            <button class="carousel-control-prev" type="button" data-bs-target="#carImages" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carImages" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        }
    </div>
</div>

Rentacar/Views/Reservation/_CarSelectionThumbnail.cshtml
@model IEnumerable<Rentacar.DataModels.CarImageDataModel>

@if (Model.Count() > 0)
{
    <div class="card-img-top">
        <img src="@Model.First().Url" class="card-img-top" alt="Image of @Model.First().Car.CodeName">
    </div>
}
else
{
    <div class="card-img-top">
        <img src="/img/Car/default.png" class="card-img-top" alt="No image available">
    </div>
}

Rentacar/Views/Reservation/_FindAvailableCars.cshtml
@model IEnumerable<Rentacar.BusinessModels.Car.CarDetailsBusinessModel>

@foreach (var car in Model)
{
    <div class="card" style="width: 18rem;">
        @await Html.PartialAsync("_CarSelectionThumbnail", car.Images)
        <div class="card-body">
            <p>@car.ManufacturedYear @car.CarManufacturerName @car.CarModelName - @car.CodeName</p>
            <button class="btn btn-primary reservationCreateCarSelect" value="@car.ID">Select</button>
            <button class="btn btn-primary car-details" value="@car.ID" data-bs-toggle="modal" data-bs-target="#modal">Details</button>
        </div>
    </div>
}